name = "ObservationModels"
uuid = "36e58220-4bbe-4dfe-b3a4-5a64030e6065"
authors = ["shubhgup "]
version = "0.1.0"

[deps]
AdversarialDriving = "0f7eb3e9-d51f-47f4-b915-6157e1c8ce29"
AutomotiveSimulator = "6aa42d20-6c96-11ea-1103-339224409280"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
